# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pIq29wvyorVNfuJhXJKi7_1FkSdTM9pE
"""

#Sorting a 3 Dimensional np array

import numpy as np
a=np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(np.sort(a))

#Searching an array for a value

a=np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
b=np.where(a==3)
print(b)